# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-07 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('sigla_estado', models.CharField(blank=True, max_length=2, null=True)),
                ('numero_de_torcedores', models.IntegerField(blank=True, null=True)),
                ('numero_de_titulos', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
