# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-23 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0002_auto_20180823_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
