# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-23 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0004_auto_20180823_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
